// src/App.svelte
<script>
  import "normalize.css";
  import sounds from "./sounds";
  import EmojiButton from "./EmojiButton.svelte";
</script>

<style>
  main {
    background: #ecf0f1;
    min-height: 100vh;
    width: 100%;
  }

  @media (prefers-color-scheme: dark) {
    main {
      background: #34495e;
    }
  }

  ul {
    list-style: none;
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(4rem, 1fr));
    grid-gap: 2rem;
    padding: 2rem;
  }

  li {
    overflow-x: hidden;
    display: inline-block;
    margin-bottom: 1rem;
    text-align: center;
  }
</style>

<main>
  <ul>
    {#each sounds as sound}
      <li>
        <EmojiButton {...sound} />
      </li>
    {/each}
  </ul>
</main>

// src/App.jsx
import React from 'react';
import styled from 'styled-components';
import EmojiButton from './EmojiButton';
import sounds from './sounds';

const Background = styled.div`
  background: #ecf0f1;
  min-height: 100vh;
  width: 100%;

  @media (prefers-color-scheme: dark) {
    background: #34495e;
  }
`;

const FlexContainer = styled.div`
  max-width: 100%;
  padding: 1rem;
`;

const OneFourthCell = styled.div`
  width: 25%;
  overflow-x: hidden;
  display: inline-block;
  margin-bottom: 1rem;
  text-align: center;
`;

const App = () => (
  <Background>
    <FlexContainer>
      {sounds.map((item, i) => (
        <OneFourthCell key={i}>
          <EmojiButton {...item} />
        </OneFourthCell>
      ))}
    </FlexContainer>
  </Background>
);

export default App;
